### ISSUE TITLE
Allow configuring multiple admins

### ISSUE THREAD

**Issue by spuder** [cvent/octopus-deploy-cookbook#112]
The `admin_user` property only takes a string

It would be nice if you could pass in multiple admins

```ruby
admin_user ['foo','bar']
```

Additionally it would be nice if the admin_user could take a hash that included email and password options

https://octopus.com/docs/api-and-integration/octopus.server.exe-command-line/admin

```json
admin_user [
  {
    "name": "foo",
    "email": "foo@example.com",
    "password": "correct-horse-battery-staple"
  }
]
```

**Comment by brentm5** [comment]
To be honest this becomes less of a priority as most of this is simply done from an initial setup perspective.  I think long term it makes sense to make another resource or split out the management of auth providers into its own resource or action on the server.  (this also is only needed for new octopus deploy clusters because these settings are in the database.
