### ISSUE TITLE
How to always use the latest version of the tentacle

### ISSUE THREAD

**Issue by reidca** [cvent/octopus-deploy-cookbook#127]
We deploy our infrastructure on a daily basis and the tentacle is always out of date because it is a hard coded parameter defined in the recipe.

How can you set the recipe to always use the latest version instead of a fixed version? It seems the version property is required.

**Comment by spuder** [comment]
I don't think octopus offers a 'latest' download link. 
Even if they did, pinning your versions is a good thing, since in large releases the tentacle isn't guaranteed to be backwards compatible. 

You can always turn off chef updates by using the `upgrades_enabled` attribute, and then use the octopus gui to upgrade servers
```

octopus_deploy_tentacle 'Tentacle' do
  action [:install, :configure, :register]
   ......
  upgrades_enabled false
end
```

**Comment by brentm5** [comment]
Yup thats exactly what the upgrades_enabled flag were designed to accomplish.  Also with Octopus Deploy 4.0   There are new options around updating tentacles.

![image](https://user-images.githubusercontent.com/1045510/36802514-194761fa-1c83-11e8-8470-d32d22a65f36.png)
