### ISSUE TITLE
No resource for service_name provider

### ISSUE THREAD

**Issue by jmcnair51** [cvent/octopus-deploy-cookbook#69]
This is more of a feature request.  You currently have the provider for service_name set to service_name(instance) which yields the result "OctopusDeploy Tentacle - Machine Name" as the actual windows service name.  The issue arises when this configuration attempts to perform a service name check (or not if block) and because I cannot override this value it causes my wrapper to error out.  This is due to inconsistencies in how you define the service name and how the service has been deployed in my environment.

**Comment by brentm5** [comment]
I am not sure if I am following you correctly. You want the ability to specify a service name override.  I am not sure if that makes sense since octopus deploy does not even allow you to change the name when you create instances of a tentacle.  What does your resource block look like which is not working?

**Comment by jmcnair51** [comment]
In you providers.rb you have set the value "service_name = service_name(instance)".  As an example this would name my tentacle service "OctopusDeploy Tentacle - WIN-NCHKE839".  However, in our environment when the tentacles have been manually setup on the nodes the service name is only "OctopusDeploy Tentacle".  This causes an issue when the recipe compiles and checks the not_if block "not_if { ::Win32::Service.exists?(service_name) }" specifically looking for "OctopusDeploy Tentacle - WIN-NCHKE839" which would evaluate as false although the tentacle service is already installed just with a slightly different name like "OctopusDeploy Tentacle".  This causes any node that runs this recipe to error out due to the service name being slightly different than is prescribed in your providers.rb file.

**Comment by brentm5** [comment]
In the provider the instance is either passed in or defaulted.  So the only way what you are saying could happen is if you did something like this.

```
octopus_deploy_tentacle 'default' do
  action [:install, :configure]
  instance 'WIN-NCHKE839'
  ...
end
```

In this example the instance name is being used to create multiple instances of the tentacle on the system.  If there is a bug in how this works it would be beneficial to fix it.  Currently we do not do that here which is why we haven't really had to go down that code path.  If you only have one tentacle instance on the machine you are trying to install you should just not pass in the instance name.

**Comment by jmcnair51** [comment]
Sorry @brentm5 for the delayed response.  Your suggestion did solve my issue, so thank you for your help. For lack of knowledge,  I was under the impression that the instance name was a mandatory input.  However, it is still possible to have both a service named OctopusDeploy Tentacle and OctopusDeploy Tentacle - Instance Name, so it would make it more flexible to be able to use a wildcard or explicitly define your service name.  Thanks again and you can close this.

**Comment by brentm5** [comment]
No problem.  Glad I could help!
